# Generated by Django 4.2.7 on 2023-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
