# Generated by Django 4.2.7 on 2023-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0002_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
